#include "globals.h"

int SCALE;
ULONGINT_T TOT_VERTICES;
int MAX_CLIQUE_SIZE;
int MAX_PARAL_EDGES;
ULONGINT_T MAX_INT_WEIGHT;
char* SOUGHT_STRING;
int MAX_STRLEN;
float PERC_INT_WEIGHTS;
float PROB_UNIDIRECTIONAL;
float PROB_INTERCL_EDGES;
int SUBGR_EDGE_LENGTH;
int MAX_CLUSTER_SIZE;
int MAX_STRLEN;
int K3_DS;
