SIMPLE_DIR  =  ..

EXTRA_CLEAN = $(LIBSIMPLE)

OPT         = -O$(O_LEVEL)
# OPT       = -g

include $(SIMPLE_DIR)/Makefile.mk

default : $(POE_CFG) objclean $(LIBSIMPLE)

$(LIBSIMPLE): $(SIMPLELIBPOBJS)
	@$(RM) -f $(SIMPLELIBDIR)/$(LIBSIMPLE)
	$(AR) r$(ARZ) $(SIMPLELIBDIR)/$(LIBSIMPLE) $(SIMPLELIBPOBJS)
ifeq (,$(findstring SGI,$(TARGET_ARCH)))
	$(RANLIB) $(SIMPLELIBDIR)/$(LIBSIMPLE)
endif




# DO NOT DELETE

obj/alg_load.o: /usr/include/stdio.h /usr/include/iso/stdio_iso.h
obj/alg_load.o: /usr/include/sys/feature_tests.h /usr/include/sys/isa_defs.h
obj/alg_load.o: /usr/include/sys/va_list.h /usr/include/stdio_tag.h
obj/alg_load.o: /usr/include/stdio_impl.h mach_def.h simple.h umd.h
obj/alg_load.o: /usr/include/stdlib.h /usr/include/iso/stdlib_iso.h
obj/alg_load.o: /usr/include/ctype.h /usr/include/iso/ctype_iso.h
obj/alg_load.o: /usr/include/errno.h /usr/include/sys/errno.h
obj/alg_load.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
obj/alg_load.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
obj/alg_load.o: /usr/include/sys/time.h /usr/include/sys/time.h
obj/alg_load.o: /usr/include/sys/resource.h /usr/include/math.h
obj/alg_load.o: /usr/include/iso/math_iso.h /usr/include/string.h
obj/alg_load.o: /usr/include/iso/string_iso.h
obj/alg_load.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi.h
obj/alg_load.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpidefs.h
obj/alg_load.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpio.h
obj/alg_load.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi_errno.h
obj/alg_load.o: /usr/local/pkg/mpich/mpich-1.1.2/include/binding.h types.h
obj/alg_load.o: /usr/include/pthread.h /usr/include/sched.h smp_node.h
obj/alg_load.o: timing.h
obj/alg_load.o: /research/etheos/kamesh/research/sprng2.0/include/sprng.h
obj/alg_load.o: /research/etheos/kamesh/research/sprng2.0/include/interface.h
obj/alg_load.o: alg_load.h
obj/alg_radix_smp.o: /usr/include/stdio.h /usr/include/iso/stdio_iso.h
obj/alg_radix_smp.o: /usr/include/sys/feature_tests.h
obj/alg_radix_smp.o: /usr/include/sys/isa_defs.h /usr/include/sys/va_list.h
obj/alg_radix_smp.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
obj/alg_radix_smp.o: alg_radix_smp.h simple.h umd.h /usr/include/stdlib.h
obj/alg_radix_smp.o: /usr/include/iso/stdlib_iso.h /usr/include/ctype.h
obj/alg_radix_smp.o: /usr/include/iso/ctype_iso.h /usr/include/errno.h
obj/alg_radix_smp.o: /usr/include/sys/errno.h /usr/include/sys/types.h
obj/alg_radix_smp.o: /usr/include/sys/machtypes.h
obj/alg_radix_smp.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
obj/alg_radix_smp.o: /usr/include/sys/time.h /usr/include/sys/time.h
obj/alg_radix_smp.o: /usr/include/sys/resource.h /usr/include/math.h
obj/alg_radix_smp.o: /usr/include/iso/math_iso.h /usr/include/string.h
obj/alg_radix_smp.o: /usr/include/iso/string_iso.h
obj/alg_radix_smp.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi.h
obj/alg_radix_smp.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpidefs.h
obj/alg_radix_smp.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpio.h
obj/alg_radix_smp.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi_errno.h
obj/alg_radix_smp.o: /usr/local/pkg/mpich/mpich-1.1.2/include/binding.h
obj/alg_radix_smp.o: mach_def.h types.h /usr/include/pthread.h
obj/alg_radix_smp.o: /usr/include/sched.h smp_node.h timing.h
obj/alg_radix_smp.o: /research/etheos/kamesh/research/sprng2.0/include/sprng.h
obj/alg_radix_smp.o: /research/etheos/kamesh/research/sprng2.0/include/interface.h
obj/alg_random.o: alg_random.h simple.h umd.h /usr/include/stdio.h
obj/alg_random.o: /usr/include/iso/stdio_iso.h
obj/alg_random.o: /usr/include/sys/feature_tests.h
obj/alg_random.o: /usr/include/sys/isa_defs.h /usr/include/sys/va_list.h
obj/alg_random.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
obj/alg_random.o: /usr/include/stdlib.h /usr/include/iso/stdlib_iso.h
obj/alg_random.o: /usr/include/ctype.h /usr/include/iso/ctype_iso.h
obj/alg_random.o: /usr/include/errno.h /usr/include/sys/errno.h
obj/alg_random.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
obj/alg_random.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
obj/alg_random.o: /usr/include/sys/time.h /usr/include/sys/time.h
obj/alg_random.o: /usr/include/sys/resource.h /usr/include/math.h
obj/alg_random.o: /usr/include/iso/math_iso.h /usr/include/string.h
obj/alg_random.o: /usr/include/iso/string_iso.h
obj/alg_random.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi.h
obj/alg_random.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpidefs.h
obj/alg_random.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpio.h
obj/alg_random.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi_errno.h
obj/alg_random.o: /usr/local/pkg/mpich/mpich-1.1.2/include/binding.h
obj/alg_random.o: mach_def.h types.h /usr/include/pthread.h
obj/alg_random.o: /usr/include/sched.h smp_node.h timing.h
obj/alg_random.o: /research/etheos/kamesh/research/sprng2.0/include/sprng.h
obj/alg_random.o: /research/etheos/kamesh/research/sprng2.0/include/interface.h
obj/simple-f-main.o: simple.h umd.h /usr/include/stdio.h
obj/simple-f-main.o: /usr/include/iso/stdio_iso.h
obj/simple-f-main.o: /usr/include/sys/feature_tests.h
obj/simple-f-main.o: /usr/include/sys/isa_defs.h /usr/include/sys/va_list.h
obj/simple-f-main.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
obj/simple-f-main.o: /usr/include/stdlib.h /usr/include/iso/stdlib_iso.h
obj/simple-f-main.o: /usr/include/ctype.h /usr/include/iso/ctype_iso.h
obj/simple-f-main.o: /usr/include/errno.h /usr/include/sys/errno.h
obj/simple-f-main.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
obj/simple-f-main.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
obj/simple-f-main.o: /usr/include/sys/time.h /usr/include/sys/time.h
obj/simple-f-main.o: /usr/include/sys/resource.h /usr/include/math.h
obj/simple-f-main.o: /usr/include/iso/math_iso.h /usr/include/string.h
obj/simple-f-main.o: /usr/include/iso/string_iso.h
obj/simple-f-main.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi.h
obj/simple-f-main.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpidefs.h
obj/simple-f-main.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpio.h
obj/simple-f-main.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi_errno.h
obj/simple-f-main.o: /usr/local/pkg/mpich/mpich-1.1.2/include/binding.h
obj/simple-f-main.o: mach_def.h types.h /usr/include/pthread.h
obj/simple-f-main.o: /usr/include/sched.h smp_node.h timing.h
obj/simple-f-main.o: /research/etheos/kamesh/research/sprng2.0/include/sprng.h
obj/simple-f-main.o: /research/etheos/kamesh/research/sprng2.0/include/interface.h
obj/simple-f-main.o: simple-f-defs.h
obj/simple-f.o: simple.h umd.h /usr/include/stdio.h
obj/simple-f.o: /usr/include/iso/stdio_iso.h /usr/include/sys/feature_tests.h
obj/simple-f.o: /usr/include/sys/isa_defs.h /usr/include/sys/va_list.h
obj/simple-f.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
obj/simple-f.o: /usr/include/stdlib.h /usr/include/iso/stdlib_iso.h
obj/simple-f.o: /usr/include/ctype.h /usr/include/iso/ctype_iso.h
obj/simple-f.o: /usr/include/errno.h /usr/include/sys/errno.h
obj/simple-f.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
obj/simple-f.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
obj/simple-f.o: /usr/include/sys/time.h /usr/include/sys/time.h
obj/simple-f.o: /usr/include/sys/resource.h /usr/include/math.h
obj/simple-f.o: /usr/include/iso/math_iso.h /usr/include/string.h
obj/simple-f.o: /usr/include/iso/string_iso.h
obj/simple-f.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi.h
obj/simple-f.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpidefs.h
obj/simple-f.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpio.h
obj/simple-f.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi_errno.h
obj/simple-f.o: /usr/local/pkg/mpich/mpich-1.1.2/include/binding.h mach_def.h
obj/simple-f.o: types.h /usr/include/pthread.h /usr/include/sched.h
obj/simple-f.o: smp_node.h timing.h
obj/simple-f.o: /research/etheos/kamesh/research/sprng2.0/include/sprng.h
obj/simple-f.o: /research/etheos/kamesh/research/sprng2.0/include/interface.h
obj/simple-f.o: simple-f-defs.h
obj/simple.o: mach_def.h /usr/include/sys/sysinfo.h /usr/include/sys/types.h
obj/simple.o: /usr/include/sys/isa_defs.h /usr/include/sys/feature_tests.h
obj/simple.o: /usr/include/sys/machtypes.h /usr/include/sys/int_types.h
obj/simple.o: /usr/include/sys/select.h /usr/include/sys/time.h
obj/simple.o: /usr/include/sys/time.h /usr/include/sys/t_lock.h
obj/simple.o: /usr/include/sys/machlock.h /usr/include/sys/param.h
obj/simple.o: /usr/include/sys/unistd.h /usr/include/sys/mutex.h
obj/simple.o: /usr/include/sys/rwlock.h /usr/include/sys/semaphore.h
obj/simple.o: /usr/include/sys/condvar.h simple.h umd.h /usr/include/stdio.h
obj/simple.o: /usr/include/iso/stdio_iso.h /usr/include/sys/va_list.h
obj/simple.o: /usr/include/stdio_tag.h /usr/include/stdio_impl.h
obj/simple.o: /usr/include/stdlib.h /usr/include/iso/stdlib_iso.h
obj/simple.o: /usr/include/ctype.h /usr/include/iso/ctype_iso.h
obj/simple.o: /usr/include/errno.h /usr/include/sys/errno.h
obj/simple.o: /usr/include/sys/resource.h /usr/include/math.h
obj/simple.o: /usr/include/iso/math_iso.h /usr/include/string.h
obj/simple.o: /usr/include/iso/string_iso.h
obj/simple.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi.h
obj/simple.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpidefs.h
obj/simple.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpio.h
obj/simple.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi_errno.h
obj/simple.o: /usr/local/pkg/mpich/mpich-1.1.2/include/binding.h types.h
obj/simple.o: /usr/include/pthread.h /usr/include/sched.h smp_node.h timing.h
obj/simple.o: /research/etheos/kamesh/research/sprng2.0/include/sprng.h
obj/simple.o: /research/etheos/kamesh/research/sprng2.0/include/interface.h
obj/simple.o: alg_load.h
obj/smp_node.o: /usr/include/stdio.h /usr/include/iso/stdio_iso.h
obj/smp_node.o: /usr/include/sys/feature_tests.h /usr/include/sys/isa_defs.h
obj/smp_node.o: /usr/include/sys/va_list.h /usr/include/stdio_tag.h
obj/smp_node.o: /usr/include/stdio_impl.h /usr/include/stdlib.h
obj/smp_node.o: /usr/include/iso/stdlib_iso.h /usr/include/pthread.h
obj/smp_node.o: /usr/include/sys/types.h /usr/include/sys/machtypes.h
obj/smp_node.o: /usr/include/sys/int_types.h /usr/include/sys/select.h
obj/smp_node.o: /usr/include/sys/time.h /usr/include/sys/time.h
obj/smp_node.o: /usr/include/sched.h /usr/include/errno.h
obj/smp_node.o: /usr/include/sys/errno.h mach_def.h smp_node.h types.h
obj/smp_node.o: /usr/include/ctype.h /usr/include/iso/ctype_iso.h
obj/smp_node.o: /usr/include/sys/resource.h /usr/include/math.h
obj/smp_node.o: /usr/include/iso/math_iso.h /usr/include/string.h
obj/smp_node.o: /usr/include/iso/string_iso.h
obj/types.o: /usr/include/stdio.h /usr/include/iso/stdio_iso.h
obj/types.o: /usr/include/sys/feature_tests.h /usr/include/sys/isa_defs.h
obj/types.o: /usr/include/sys/va_list.h /usr/include/stdio_tag.h
obj/types.o: /usr/include/stdio_impl.h /usr/include/stdlib.h
obj/types.o: /usr/include/iso/stdlib_iso.h types.h /usr/include/ctype.h
obj/types.o: /usr/include/iso/ctype_iso.h /usr/include/errno.h
obj/types.o: /usr/include/sys/errno.h /usr/include/sys/types.h
obj/types.o: /usr/include/sys/machtypes.h /usr/include/sys/int_types.h
obj/types.o: /usr/include/sys/select.h /usr/include/sys/time.h
obj/types.o: /usr/include/sys/time.h /usr/include/sys/resource.h
obj/types.o: /usr/include/math.h /usr/include/iso/math_iso.h
obj/types.o: /usr/include/string.h /usr/include/iso/string_iso.h mach_def.h
obj/umd-f.o: umd.h /usr/include/stdio.h /usr/include/iso/stdio_iso.h
obj/umd-f.o: /usr/include/sys/feature_tests.h /usr/include/sys/isa_defs.h
obj/umd-f.o: /usr/include/sys/va_list.h /usr/include/stdio_tag.h
obj/umd-f.o: /usr/include/stdio_impl.h /usr/include/stdlib.h
obj/umd-f.o: /usr/include/iso/stdlib_iso.h /usr/include/ctype.h
obj/umd-f.o: /usr/include/iso/ctype_iso.h /usr/include/errno.h
obj/umd-f.o: /usr/include/sys/errno.h /usr/include/sys/types.h
obj/umd-f.o: /usr/include/sys/machtypes.h /usr/include/sys/int_types.h
obj/umd-f.o: /usr/include/sys/select.h /usr/include/sys/time.h
obj/umd-f.o: /usr/include/sys/time.h /usr/include/sys/resource.h
obj/umd-f.o: /usr/include/math.h /usr/include/iso/math_iso.h
obj/umd-f.o: /usr/include/string.h /usr/include/iso/string_iso.h
obj/umd-f.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi.h
obj/umd-f.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpidefs.h
obj/umd-f.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpio.h
obj/umd-f.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi_errno.h
obj/umd-f.o: /usr/local/pkg/mpich/mpich-1.1.2/include/binding.h mach_def.h
obj/umd-f.o: types.h
obj/umd.o: /usr/include/stdio.h /usr/include/iso/stdio_iso.h
obj/umd.o: /usr/include/sys/feature_tests.h /usr/include/sys/isa_defs.h
obj/umd.o: /usr/include/sys/va_list.h /usr/include/stdio_tag.h
obj/umd.o: /usr/include/stdio_impl.h /usr/include/stdlib.h
obj/umd.o: /usr/include/iso/stdlib_iso.h /usr/include/ctype.h
obj/umd.o: /usr/include/iso/ctype_iso.h /usr/include/errno.h
obj/umd.o: /usr/include/sys/errno.h /usr/include/sys/types.h
obj/umd.o: /usr/include/sys/machtypes.h /usr/include/sys/int_types.h
obj/umd.o: /usr/include/sys/select.h /usr/include/sys/time.h
obj/umd.o: /usr/include/sys/time.h /usr/include/sys/resource.h
obj/umd.o: /usr/include/math.h /usr/include/iso/math_iso.h
obj/umd.o: /usr/include/string.h /usr/include/iso/string_iso.h
obj/umd.o: /usr/include/sys/socket.h /usr/include/sys/uio.h
obj/umd.o: /usr/include/sys/netconfig.h /usr/include/netinet/in.h
obj/umd.o: /usr/include/sys/stream.h /usr/include/sys/vnode.h
obj/umd.o: /usr/include/sys/t_lock.h /usr/include/sys/machlock.h
obj/umd.o: /usr/include/sys/param.h /usr/include/sys/unistd.h
obj/umd.o: /usr/include/sys/mutex.h /usr/include/sys/rwlock.h
obj/umd.o: /usr/include/sys/semaphore.h /usr/include/sys/condvar.h
obj/umd.o: /usr/include/sys/time_impl.h /usr/include/sys/cred.h
obj/umd.o: /usr/include/vm/seg_enum.h /usr/include/sys/poll.h
obj/umd.o: /usr/include/sys/strmdep.h /usr/include/sys/model.h
obj/umd.o: /usr/include/sys/strft.h /usr/include/sys/byteorder.h
obj/umd.o: /usr/include/sys/un.h /usr/include/net/if_dl.h
obj/umd.o: /usr/include/netinet/tcp.h /usr/include/sys/inttypes.h
obj/umd.o: /usr/include/sys/int_limits.h /usr/include/sys/int_const.h
obj/umd.o: /usr/include/sys/int_fmtio.h /usr/include/netdb.h
obj/umd.o: /usr/include/fcntl.h /usr/include/sys/fcntl.h umd.h
obj/umd.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi.h
obj/umd.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpidefs.h
obj/umd.o: /usr/local/pkg/mpich/mpich-1.1.2/build/solaris/ch_p4/include/mpio.h
obj/umd.o: /usr/local/pkg/mpich/mpich-1.1.2/include/mpi_errno.h
obj/umd.o: /usr/local/pkg/mpich/mpich-1.1.2/include/binding.h mach_def.h
obj/umd.o: types.h /usr/include/unistd.h /usr/include/pthread.h
obj/umd.o: /usr/include/sched.h
