EXECS = prefixBlock

SIMPLE_DIR = ..

OPT         = -O$(O_LEVEL)
# OPT       = -g

include $(SIMPLE_DIR)/Makefile.smp.mk

# DO NOT DELETE

obj/prefixBlock.o: ../include/simple.h /usr/include/pthread.h
obj/prefixBlock.o: /usr/include/sys/types.h /usr/include/sys/isa_defs.h
obj/prefixBlock.o: /usr/include/sys/feature_tests.h
obj/prefixBlock.o: /usr/include/sys/machtypes.h /usr/include/sys/int_types.h
obj/prefixBlock.o: /usr/include/sys/select.h /usr/include/sys/time.h
obj/prefixBlock.o: /usr/include/sys/time.h /usr/include/sched.h
obj/prefixBlock.o: ../include/mach_def.h ../include/smp_node.h
obj/prefixBlock.o: /usr/include/stdio.h /usr/include/iso/stdio_iso.h
obj/prefixBlock.o: /usr/include/sys/va_list.h /usr/include/stdio_tag.h
obj/prefixBlock.o: /usr/include/stdio_impl.h /usr/include/stdlib.h
obj/prefixBlock.o: /usr/include/iso/stdlib_iso.h ../include/types.h
obj/prefixBlock.o: /usr/include/ctype.h /usr/include/iso/ctype_iso.h
obj/prefixBlock.o: /usr/include/errno.h /usr/include/sys/errno.h
obj/prefixBlock.o: /usr/include/sys/resource.h /usr/include/math.h
obj/prefixBlock.o: /usr/include/iso/math_iso.h /usr/include/string.h
obj/prefixBlock.o: /usr/include/iso/string_iso.h ../include/timing.h
obj/prefixBlock.o: /research/etheos/kamesh/research/sprng2.0/include/sprng.h
obj/prefixBlock.o: /research/etheos/kamesh/research/sprng2.0/include/interface.h
